### ISSUE TITLE
ITMS-90535 Unable to publish iOS app

### ISSUE THREAD

**Issue by schwips** [robovm/robovm-robopods#61]
I get the this errors when I try to publish my app to apple app store.
I'm using Xcode 7.1.1 and installed latest Google Play Games/Google SignIn Robopods (1.9.1-SNAPSHOT)

1 package(s) were not uploaded because they had problems:
	/var/folders/n8/2_pl6r9x61vbm3mz4jm8ykz40000gn/T/884F2253-C7E5-4E8C-B429-5C4551C6306F/982835004.itmsp - Error Messages:
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle/GPPCommonSharedResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle/GPPShareboxSharedResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/gpg.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by knepe** [comment]
You need to edit all bundles and remove CFBundleExecutable from their Info.plist

**Comment by knepe** [comment]
This should be fixed by the developer though if it can. It's very annow

**Comment by schwips** [comment]
how can I do that?

**Comment by knepe** [comment]
Right click your ipa file and choose Show package content then do the same with all those .bundle files and edit their info.plist. Then I think need to sign the package again, I use iResign it's on github

**Comment by Hydrogenhax** [comment]
Thanks for the answer. Officially ran out of ideas and I saw this, saved me from additional trial and error to figure this out.

**Comment by knepe** [comment]
Here is a guide on how to re-sign the ipa http://dev.mlsdigital.net/posts/how-to-resign-an-ios-app-from-external-developers/ in case someone needs that

**Comment by BlueRiverInteractive** [comment]
I think I have fixed this problem at the root now. I have commented out the CFBundleExecutable key in the Info.plist of gpg.bundle. I also remove the dependency on GooglePlus which has been deprecated anyway, so this should fix the other errors.
Please let me know if the errors are gone with the latest 1.12.1-SNAPSHOT version.

**Comment by ldthai** [comment]
i still get this error with the latest 1.12.1-SNAPSHOT

**Comment by schwips** [comment]
The gpg.bundle seems to be fine now. But still the same error with the GooglePlus.bundle

**Comment by schwips** [comment]
Please also remove CFBundleExecutable in 

GPPCommonSharedResources.bundle and

GPPShareboxSharedResources.bundle

**Comment by joseBarreto** [comment]
> Rename your .ipa file to .zip and open zip file and choose Show package content then do the same with all those .bundle files and edit their info.plist. Then compress the Payload folder again and rename the .zip to .ipa. Then I think need to sign the package again, I use iResign it's on github

You have no idea how saved the rest of my day after hours suffering from this error.
But using MessageSDKFramework with CometChat
